version: "3.1"

services:
  # MongoDB instance
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: metadataadmin
      MONGO_INITDB_DATABASE: metadata
    volumes:
      - ./server/src/setup.js:/docker-entrypoint-initdb.d/setup.js:ro

  # mongo-express instance to view database
  viewer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: metadataadmin
      ME_CONFIG_MONGODB_URL: mongodb://admin:metadataadmin@database:27017/

  # Prometheus for metrics and monitoring
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.web.yml:/etc/prometheus/prometheus.web.yml
    environment:
      - web.config.file=/etc/prometheus/prometheus.web.yml

  # Grafana for dashboard
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000
