version: '3.1'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: metadataadmin
      MONGO_INITDB_DATABASE: metadata
    volumes:
      - ./server/src/setup.js:/docker-entrypoint-initdb.d/setup.js:ro

  viewer:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: metadataadmin
      ME_CONFIG_MONGODB_URL: mongodb://admin:metadataadmin@database:27017/

  server:
    build:
      context: .
      dockerfile: ./server/server.dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database

  client:
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server