name: Test MARS Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CONNECTION_STRING: mongodb://admin:metadataadmin@localhost:27017/
  PORT: 8000

jobs:
  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["6.0"]

    steps:
    - uses: actions/checkout@v3

    - name: Start Docker containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    # Install and build the client
    - name: Install and Build Client
      working-directory: ./client
      run: |
        yarn install
        yarn build

    # Start the client
    - name: Start Client
      working-directory: ./client
      run: yarn start &

    # Start the server
    - name: Build Server
      working-directory: ./server
      run: |
        yarn
        yarn build

    # Test the server
    - name: Test Server
      working-directory: ./server
      run: |
        yarn test
    
    - name: Start Server
      working-directory: ./server
      run: yarn start &
    # Wait for the client and server to be up and running
    - name: Wait for Client
      run: sleep 10  # Adjust the sleep duration as necessary

    - name: Feature Tests (Cypress)
      id: cypress
      run: |
        yarn cypress run
      continue-on-error: true

    - name: Upload Cypress Screenshots
      if: failure() && steps.cypress.outcome == 'failure'  # Runs this step only if the Cypress step failed
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress-screenshots
