name: Deploy client

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: MARS-client
  AZURE_WEBAPP_PACKAGE_PATH: './client'
  NODE_VERSION: '16.x'

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      working-directory: ./client
      run: |
        yarn
        yarn build

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
