name: Deploy client

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env: DISABLE_CAPTURE=false

jobs:
  deploy_client:
    runs-on: ubuntu-latest
    name: Deploy client
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create .env file for client
        working-directory: client
        run: |
          touch .env
          echo "REACT_APP_PUBLIC_POSTHOG_KEY=${{ secrets.REACT_APP_PUBLIC_POSTHOG_KEY }}" >> .env
          echo "REACT_APP_PUBLIC_POSTHOG_HOST=${{ secrets.REACT_APP_PUBLIC_POSTHOG_HOST }}" >> .env
          echo "DISABLE_CAPTURE=${{ env.DISABLE_CAPTURE }}" >> .env

      - name: Deploy to Azure
        id: deploy-static-web-app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_WAVE_02CDDA510 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/client"
          api_location: "/server"
          output_location: "/dist"
